String? token = '';
String? refreshToken = '';
String? id = '';
String? shareId = '';
var roomId = '';
String? email1 = '';
int? price;
const taskId = 'id';
const taskReview = 'review';
const taskTitle = 'title';
const taskImportance = 'importance';
const taskPrice = 'price';
const taskDesc = 'desc';
const taskStatus = 'status';
